spring:
  application:
    name: gateway-server
  datasource:
    username: root
    password: root
    url:
      jdbc : postgresql://localhost:9999/BanklyGateway
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

    show-sql: true
    hibernate.ddl-auto: update
  groovy:
    template:
      configuration.use-double-quotes: true
  sql:
    init:
      mode: never
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
server:
  port: 9102
  #Eureka
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:9100/eureka/
logging:
  level:
    * : info
  spring:
    jpa:
      hibernate:
        *: error
jwt-secret: "this is jwt secret"
#logging.level.org.springframework.boot.autoconfigure.h2=INFO
#logging.level.org.springframework.boot.web.embedded.tomcat=INFO
#spring.h2.console.enabled=true
