#
spring:
  application:
    name: gateway-server
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: products
#          uri: http://localhost:9001/Produits
#          predicates:
#            - Path=/products
server:
  port: 9099
  #Eureka
#eureka:
#  client:
#    serviceURL:
#      defaultZone: http://localhost:9102/eureka/
#management:
#  endpoint:
#    gateway:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: gateway
#
